### ISSUE TITLE
Applicable Windows Build

### ISSUE THREAD

**Issue by funnybananas** [Cerbersec/KillDefenderBOF#1]
Can't seem to recreate on 20H2. Fails to open process token associated with MsMpEng.exe. 
Just curious which build you tested this on, thanks!

**Comment by Cerbersec** [comment]
This was tested on 20H1, Build 19041.

Did you execute in NT AUTHORITY\SYSTEM context?

**Comment by funnybananas** [comment]
Dang, no I didn't. Was executing under high integrity Administrator context. Works fine under SYSTEM context on 20H2 and 21H2. Great work on this, and thanks for the quick reply.
